language: rust
rust:
- nightly
- stable

script:
- cargo build --all --verbose
- cargo test --all --verbose
- cargo build -all --verbose --features serialize
- cargo test --all --verbose --features serialize
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    cargo bench --all --verbose --no-run;
  fi

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  cargo doc --all &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cdff2f522a8c4588a82a
    on_success: always
    on_failure: always
    on_start: never
